--- 
Administrator: 
  authentication: 
    type: op
  class: Administrator
Scorekeeper: 
  class: Scorekeeper
Insulter: 
  class: Insulter
Encourager:
  class: Encourager
  respond_to_private_messages: true
